server:
  port: 8090
spring:
  datasource:
    url: jdbc:sqlite:d:/test.db
    driver-class-name: org.sqlite.JDBC
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000ms
mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    jdbc-type-for-null: 'null'

cacheexpire:
  captcha: 100
  account: 3600
  order: 36000

counter:
  dataCenterId: 0
  workerId: 0
  #机房ID  - 为生成全局唯一ID
  #机柜ID
  memberid: 0
  checksum: com.client.checksum.CheckSum
  bodycodec: com.client.codec.BodyCodec
  msgcodec: com.client.codec.MsgCodec
  #订阅总线数据 - oms-engine用mqtt(订阅/发布模式）发布的market data和成交数据
  subbusip: 127.0.0.1
  subbusport: 1883
  #websocket地址 UI跟后端传送数据
  pubport: 8501

gateway:
  senderIp: 127.0.0.1
  senderPort: 8091
  gatewayId: 1001





